version: "3.8"

services:
  mongo:
    image: mongo
    restart: always
    container_name: db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: aaa123
    volumes:
      - ./mongo_data/:/data/db/